### ISSUE TITLE
NotFoundException: checked vs unchecked

### ISSUE THREAD

**Issue by thatging3rkid** [FIRST-Team-1699/ini-reader#5]
Currently, a ConfigFile contains ConfigSections, which in turn contain ConfigLines<>. This level of separation was designed in order to decrease the number of ini files needed on the robot itself, instead only one ConfigFile is used and multiple ConfigSections are used to contain data for separate parts of the robot or certain autonomous configurations. But, when getting a value from a ConfigSection, one of two functions can be used: `.getSection(int a)` and `.getSection(String name)`. `.getSection(int a)` returns `null` if the given index is out of bounds (and the `.size()` method should be used to make sure this does not happen). But, the `.getSection(String name)` raises a NotFoundException if the given name does not exist in the ConfigFile or ConfigSection. How should this exception be handled, should it be checked (forced to be in a try/catch or declared in the method header) or should it be unchecked (crashes code)? Also, should the way that `.getSection(int a)` returns an error be changed?

**Comment by seth-crampton** [comment]
I think the two methods should be consistent with how they handle errors. How does the rest of the code handle a null ConfigSection? If they aren't handled particularly gracefully i would say scrap returning null on   `.getSection(int a)` and have both go unchecked. If you're relatively sure a null ConfigSection will be handled gracefully I say return null for `.getSection(String name)` and just print out a warning message whenever a null is returned for debugging purposes .

p.s. I think part of me died reading the spaghetti code of the `readFile()` method. we should refactor at some point.

**Comment by thatging3rkid** [comment]
Yeah, `readFile()` is one of those methods that was written, generics support was tacked on, and never messed with. There hasn't been a review since it was written. Now seems like a good time to do it, I can make sure it gets in 2.1rc4 or 2.2rc1 (and I would like the full release to be done by bag and tag). 

And yeah, I agree, it doesn't make sense for two methods with the same name to act differently. And for why `.getSection(int a)` returns `null`, is for:
```java
int i = 0;
ConfigLine<?> line;
while ((line = section.getLine(i) != null) {
    // .getLine(int a) acts like .getSection(int a)
    i += 1;
   // process code
}
```
Something like this would be used to generate the ArrayList for the autonomous code's input. Now, I could change it so that there is a `.toStringList()` method (or any other applicable methods) that generates a list of all the ConfigLines in that section, then get rid of the `.getLine(int a)`. The question then would be if the `.getSection(int a)` needs to be replaced, and then get back to checked vs unchecked. But, I'll wait for @squirlemaster42 to put in his input.

**Comment by squirlemaster42** [comment]
I think that it should be check; you can't drive a crashed robot.
