### ISSUE TITLE
Refactor readFile

### ISSUE THREAD

**Issue by seth-crampton** [FIRST-Team-1699/ini-reader#6]
So 200 lines of code is a bit excessive for a single method.  We should at least create helper methods that make the code more readable. I was thinking we would pull the parsing out of the lines out of the method. That might require us to make rawConfigSection and/or rawConfigLine objects that hold unparsed versions or ConfigSection and/or ConfigLine objects. 

We could also create new classes to specifically handle building up the ConfigSecion and ConfigLine Objects. Following the [Builder Design Pattern](https://en.wikipedia.org/wiki/Builder_pattern) should help implement it this way . 

This is a low priority but I might make a new branch to try to clean it up and make it more manageable without killing it.

**Comment by thatging3rkid** [comment]
I will work on this for the next pre-release.
